# Generated by Django 4.0.4 on 2022-06-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_product_owner_product_postdate_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdate',
            name='date',
            field=models.CharField(default='0000-00-00', max_length=200),
        ),
    ]
