# Generated by Django 4.0.4 on 2022-06-13 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_product_postdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='postDate',
            field=models.DateField(default=datetime.date(2022, 8, 1)),
        ),
    ]
