# Generated by Django 4.0.4 on 2022-06-14 06:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_product_postdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='postDate',
        ),
        migrations.AddField(
            model_name='product',
            name='post_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
