# Generated by Django 4.0.4 on 2022-06-14 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_product_postdate_product_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='post_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 14, 8, 15, 18, 726255)),
        ),
    ]
