# Generated by Django 4.0.4 on 2022-06-14 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_product_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='post_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 8, 2, 8, 15, 41, 800920)),
        ),
    ]
