# Generated by Django 4.0.4 on 2022-06-14 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_product_post_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostDate',
        ),
        migrations.AlterField(
            model_name='product',
            name='post_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 21, 8, 19, 2, 596363)),
        ),
    ]
